version: '3'
services:
  postgres:
    image: "postgres:14.7"
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'goflyway'
    ports:
      - '5432:5432'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mysql:
    image: "mysql:8.1.0"
    environment:
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'goflyway'
    ports:
      - '3306:3306'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "password#999"
    ports:
      - '1433:1433'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
      
